export interface ScenarioTemplate {
  id: string;
  name: string;
  description: string;
  category: string;
  scenario_family: string;
  scenario_pattern: string;
  scenario_statement: string;
  threat_community: string;
  threat_action: string;
  loss_event_type: string;
  loss_forms: string;
  existing_controls_hint: string;
  tef_low: number;
  tef_ml: number;
  tef_high: number;
  vuln_low: number;
  vuln_ml: number;
  vuln_high: number;
  primary_loss_low: number;
  primary_loss_ml: number;
  primary_loss_high: number;
  secondary_event_prob: number;
  secondary_loss_low: number;
  secondary_loss_ml: number;
  secondary_loss_high: number;
}

export const SCENARIO_TEMPLATES: ScenarioTemplate[] = [
  {
    id: 'tmpl-phishing-admin',
    name: 'Admin Account Takeover via Phishing',
    description: 'External attacker compromises an administrator account through phishing, gaining elevated access to critical systems.',
    category: 'Identity & Access',
    scenario_family: 'Identity compromise',
    scenario_pattern: 'Phishing-driven admin account takeover',
    scenario_statement: 'External attacker uses phishing to compromise an administrator account, enabling unauthorized access to sensitive systems and data.',
    threat_community: 'External attacker',
    threat_action: 'Phishing / credential harvesting',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Operational backlog and productivity loss; Reputation / brand harm',
    existing_controls_hint: 'MFA, phishing-resistant MFA for admins, email security gateway, anomaly detection, PAM',
    tef_low: 3, tef_ml: 8, tef_high: 20,
    vuln_low: 0.03, vuln_ml: 0.10, vuln_high: 0.25,
    primary_loss_low: 20000, primary_loss_ml: 125000, primary_loss_high: 800000,
    secondary_event_prob: 0.15,
    secondary_loss_low: 0, secondary_loss_ml: 250000, secondary_loss_high: 3000000,
  },
  {
    id: 'tmpl-synthetic-fraud',
    name: 'Synthetic Identity Fraud',
    description: 'Organized fraud ring creates fake identities to obtain loans or accounts that will never be repaid.',
    category: 'Fraud',
    scenario_family: 'Fraud / abuse',
    scenario_pattern: 'Synthetic identity creation for loan fraud',
    scenario_statement: 'Organized fraud ring creates synthetic identities to submit fraudulent applications, resulting in funded accounts that default.',
    threat_community: 'Organized fraud ring',
    threat_action: 'Synthetic identity creation',
    loss_event_type: 'Fraud loss',
    loss_forms: 'Fraud loss / unrecoverable funds; Incident response and investigation cost; Model remediation / re-underwriting cost',
    existing_controls_hint: 'Identity verification (KYC), credit bureau checks, fraud scoring model, velocity rules, manual review queue',
    tef_low: 5, tef_ml: 20, tef_high: 60,
    vuln_low: 0.02, vuln_ml: 0.06, vuln_high: 0.12,
    primary_loss_low: 10000, primary_loss_ml: 40000, primary_loss_high: 100000,
    secondary_event_prob: 0.08,
    secondary_loss_low: 25000, secondary_loss_ml: 150000, secondary_loss_high: 1000000,
  },
  {
    id: 'tmpl-vendor-outage',
    name: 'Critical Vendor Service Outage',
    description: 'A key third-party vendor experiences an extended outage that disrupts your business operations.',
    category: 'Third Party',
    scenario_family: 'Third-party dependency failure',
    scenario_pattern: 'Vendor service outage disrupts business process',
    scenario_statement: 'Critical vendor experiences an extended service outage, disrupting dependent business processes and causing operational backlog.',
    threat_community: 'Vendor / subservice provider',
    threat_action: 'Vendor service outage',
    loss_event_type: 'Availability loss',
    loss_forms: 'Operational backlog and productivity loss; Revenue loss from servicing disruption; Contractual liability / partner indemnification',
    existing_controls_hint: 'Vendor SLA monitoring, business continuity plan, alternative vendor relationships, degraded-mode procedures',
    tef_low: 1, tef_ml: 3, tef_high: 8,
    vuln_low: 0.20, vuln_ml: 0.50, vuln_high: 0.80,
    primary_loss_low: 10000, primary_loss_ml: 75000, primary_loss_high: 400000,
    secondary_event_prob: 0.05,
    secondary_loss_low: 0, secondary_loss_ml: 100000, secondary_loss_high: 500000,
  },
  {
    id: 'tmpl-data-misdelivery',
    name: 'Sensitive Data Sent to Wrong Recipient',
    description: 'An employee accidentally sends sensitive customer data to the wrong person via email or file share.',
    category: 'Data Protection',
    scenario_family: 'Data disclosure',
    scenario_pattern: 'Accidental data disclosure via misdelivery',
    scenario_statement: 'Negligent insider accidentally sends sensitive data to an unauthorized recipient, triggering breach notification obligations.',
    threat_community: 'Negligent insider',
    threat_action: 'Data disclosure / misdelivery',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Customer reimbursement / restitution; Regulatory response and examination cost',
    existing_controls_hint: 'DLP rules, email encryption, sensitivity labels, outbound content inspection, security awareness training',
    tef_low: 5, tef_ml: 15, tef_high: 40,
    vuln_low: 0.10, vuln_ml: 0.30, vuln_high: 0.60,
    primary_loss_low: 5000, primary_loss_ml: 30000, primary_loss_high: 150000,
    secondary_event_prob: 0.20,
    secondary_loss_low: 10000, secondary_loss_ml: 100000, secondary_loss_high: 750000,
  },
  {
    id: 'tmpl-cloud-misconfig',
    name: 'Cloud Storage Misconfiguration Exposes Data',
    description: 'A cloud storage bucket or database is misconfigured with public access, exposing sensitive data.',
    category: 'Cloud & Infrastructure',
    scenario_family: 'Cloud / platform misconfiguration',
    scenario_pattern: 'Cloud misconfiguration exposes sensitive data',
    scenario_statement: 'Cloud storage is misconfigured with overly permissive access controls, exposing sensitive data to unauthorized parties.',
    threat_community: 'Negligent insider',
    threat_action: 'Misconfiguration',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Customer reimbursement / restitution; Fines, penalties, and settlements; Reputation / brand harm',
    existing_controls_hint: 'Cloud security posture management (CSPM), infrastructure-as-code reviews, access policy automation, periodic access audits',
    tef_low: 2, tef_ml: 6, tef_high: 15,
    vuln_low: 0.05, vuln_ml: 0.15, vuln_high: 0.35,
    primary_loss_low: 15000, primary_loss_ml: 100000, primary_loss_high: 500000,
    secondary_event_prob: 0.25,
    secondary_loss_low: 50000, secondary_loss_ml: 500000, secondary_loss_high: 5000000,
  },
  {
    id: 'tmpl-access-deprov',
    name: 'Terminated Employee Retains Access',
    description: 'A terminated employee or contractor retains system access due to failed deprovisioning, enabling unauthorized actions.',
    category: 'Identity & Access',
    scenario_family: 'Privileged access misuse',
    scenario_pattern: 'Deprovisioning failure enables unauthorized access',
    scenario_statement: 'Former employee retains system access after termination due to deprovisioning failure, enabling data theft or unauthorized changes.',
    threat_community: 'Malicious insider',
    threat_action: 'Access deprovisioning failure',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Operational backlog and productivity loss; Reputation / brand harm',
    existing_controls_hint: 'Automated deprovisioning workflows, HR-IT integration, periodic access reviews, activity monitoring for dormant accounts',
    tef_low: 2, tef_ml: 5, tef_high: 12,
    vuln_low: 0.05, vuln_ml: 0.15, vuln_high: 0.30,
    primary_loss_low: 10000, primary_loss_ml: 60000, primary_loss_high: 300000,
    secondary_event_prob: 0.10,
    secondary_loss_low: 0, secondary_loss_ml: 150000, secondary_loss_high: 1000000,
  },
  {
    id: 'tmpl-bad-release',
    name: 'Bad Code Release Causes Outage',
    description: 'A flawed deployment or configuration change causes a production outage affecting customers.',
    category: 'Change Management',
    scenario_family: 'Change / release failure',
    scenario_pattern: 'Insecure or unstable release causes outage',
    scenario_statement: 'A code deployment introduces a defect that causes production outage, disrupting customer-facing services.',
    threat_community: 'Process failure',
    threat_action: 'Insecure change / release',
    loss_event_type: 'Availability loss',
    loss_forms: 'Operational backlog and productivity loss; Revenue loss from origination disruption; Technology restoration / rebuild cost',
    existing_controls_hint: 'CI/CD pipeline gates, automated testing, canary deployments, rollback procedures, change advisory board',
    tef_low: 3, tef_ml: 8, tef_high: 20,
    vuln_low: 0.10, vuln_ml: 0.25, vuln_high: 0.50,
    primary_loss_low: 10000, primary_loss_ml: 50000, primary_loss_high: 250000,
    secondary_event_prob: 0.05,
    secondary_loss_low: 0, secondary_loss_ml: 75000, secondary_loss_high: 500000,
  },
  {
    id: 'tmpl-regulatory-miss',
    name: 'Missed Regulatory Filing or Notice',
    description: 'A required regulatory filing, disclosure, or customer notice is missed or delivered late.',
    category: 'Compliance',
    scenario_family: 'Regulatory obligation failure',
    scenario_pattern: 'Missed regulatory deadline or notice requirement',
    scenario_statement: 'Internal process failure results in missed regulatory filing or late customer notice, triggering examination or enforcement action.',
    threat_community: 'Process failure',
    threat_action: 'Reporting / filing failure',
    loss_event_type: 'Compliance / obligation failure',
    loss_forms: 'Fines, penalties, and settlements; Regulatory response and examination cost; Operational backlog and productivity loss',
    existing_controls_hint: 'Compliance calendar, automated filing reminders, dual-review of submissions, regulatory change management process',
    tef_low: 1, tef_ml: 3, tef_high: 8,
    vuln_low: 0.10, vuln_ml: 0.25, vuln_high: 0.50,
    primary_loss_low: 20000, primary_loss_ml: 100000, primary_loss_high: 500000,
    secondary_event_prob: 0.30,
    secondary_loss_low: 50000, secondary_loss_ml: 300000, secondary_loss_high: 2000000,
  },
  {
    id: 'tmpl-ransomware',
    name: 'Ransomware Attack',
    description: 'Ransomware encrypts critical systems, demanding payment for decryption keys and threatening data publication.',
    category: 'Cyber Attack',
    scenario_family: 'Endpoint compromise',
    scenario_pattern: 'Ransomware encrypts critical business systems',
    scenario_statement: 'External attacker deploys ransomware that encrypts production systems, causing extended outage and threatening publication of exfiltrated data.',
    threat_community: 'External attacker',
    threat_action: 'Data exfiltration',
    loss_event_type: 'Availability loss',
    loss_forms: 'Technology restoration / rebuild cost; Operational backlog and productivity loss; Revenue loss from servicing disruption; Incident response and investigation cost; Reputation / brand harm',
    existing_controls_hint: 'Endpoint detection and response (EDR), network segmentation, offline backups, incident response plan, email filtering, user awareness training',
    tef_low: 1, tef_ml: 3, tef_high: 8,
    vuln_low: 0.02, vuln_ml: 0.08, vuln_high: 0.20,
    primary_loss_low: 100000, primary_loss_ml: 500000, primary_loss_high: 3000000,
    secondary_event_prob: 0.40,
    secondary_loss_low: 100000, secondary_loss_ml: 1000000, secondary_loss_high: 10000000,
  },
  {
    id: 'tmpl-insider-data-theft',
    name: 'Insider Data Theft Before Departure',
    description: 'An employee exfiltrates sensitive data (customer lists, IP, financials) before leaving the organization.',
    category: 'Insider Threat',
    scenario_family: 'Data disclosure',
    scenario_pattern: 'Departing employee exfiltrates sensitive data',
    scenario_statement: 'Malicious insider downloads sensitive business data before resignation, using it at a competitor or for personal gain.',
    threat_community: 'Malicious insider',
    threat_action: 'Data exfiltration',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Revenue loss from origination disruption; Contractual liability / partner indemnification; Reputation / brand harm',
    existing_controls_hint: 'DLP monitoring, USB restrictions, cloud access controls, departure risk scoring, activity monitoring for notice-period employees',
    tef_low: 2, tef_ml: 6, tef_high: 15,
    vuln_low: 0.10, vuln_ml: 0.25, vuln_high: 0.45,
    primary_loss_low: 20000, primary_loss_ml: 100000, primary_loss_high: 500000,
    secondary_event_prob: 0.15,
    secondary_loss_low: 50000, secondary_loss_ml: 300000, secondary_loss_high: 2000000,
  },
  {
    id: 'tmpl-bec-payment',
    name: 'Business Email Compromise (Payment Fraud)',
    description: 'Attacker impersonates a trusted party via email to redirect a payment or wire transfer to a fraudulent account.',
    category: 'Fraud',
    scenario_family: 'Fraud / abuse',
    scenario_pattern: 'BEC attack redirects payment to attacker-controlled account',
    scenario_statement: 'External attacker compromises or spoofs a trusted email account to socially engineer a payment redirect, diverting funds to an attacker-controlled account.',
    threat_community: 'External attacker',
    threat_action: 'Payment diversion',
    loss_event_type: 'Fraud loss',
    loss_forms: 'Fraud loss / unrecoverable funds; Incident response and investigation cost; Operational backlog and productivity loss',
    existing_controls_hint: 'Email authentication (DMARC/DKIM), payment verification callbacks, dual-approval for wire changes, employee training on BEC tactics',
    tef_low: 3, tef_ml: 10, tef_high: 25,
    vuln_low: 0.02, vuln_ml: 0.05, vuln_high: 0.12,
    primary_loss_low: 25000, primary_loss_ml: 150000, primary_loss_high: 750000,
    secondary_event_prob: 0.05,
    secondary_loss_low: 0, secondary_loss_ml: 50000, secondary_loss_high: 250000,
  },
  {
    id: 'tmpl-model-drift',
    name: 'AI/ML Model Drift Causes Unfair Outcomes',
    description: 'A credit or fraud model drifts from its validated state, producing biased or inaccurate decisions at scale.',
    category: 'AI & Model Risk',
    scenario_family: 'AI / model governance failure',
    scenario_pattern: 'Model drift causes biased or inaccurate decisioning',
    scenario_statement: 'Production model drifts from validated performance, producing systematically biased or inaccurate decisions that harm customers and create regulatory exposure.',
    threat_community: 'System failure',
    threat_action: 'Misconfiguration',
    loss_event_type: 'Compliance / obligation failure',
    loss_forms: 'Model remediation / re-underwriting cost; Fines, penalties, and settlements; Customer reimbursement / restitution; Regulatory response and examination cost',
    existing_controls_hint: 'Model monitoring dashboards, performance drift alerts, quarterly model validation, fair lending testing, model governance committee',
    tef_low: 1, tef_ml: 2, tef_high: 5,
    vuln_low: 0.10, vuln_ml: 0.25, vuln_high: 0.50,
    primary_loss_low: 50000, primary_loss_ml: 250000, primary_loss_high: 1000000,
    secondary_event_prob: 0.35,
    secondary_loss_low: 200000, secondary_loss_ml: 1000000, secondary_loss_high: 8000000,
  },
  {
    id: 'tmpl-backup-failure',
    name: 'Backup/Recovery Failure During Incident',
    description: 'When recovery is needed, backups are found to be corrupted, incomplete, or untested, extending downtime.',
    category: 'Resilience',
    scenario_family: 'Service outage / resilience failure',
    scenario_pattern: 'Backup restoration fails when needed',
    scenario_statement: 'During a production incident requiring system restoration, backups are discovered to be corrupted or incomplete, significantly extending recovery time.',
    threat_community: 'System failure',
    threat_action: 'Backup / recovery failure',
    loss_event_type: 'Availability loss',
    loss_forms: 'Technology restoration / rebuild cost; Operational backlog and productivity loss; Revenue loss from servicing disruption; Revenue loss from origination disruption',
    existing_controls_hint: 'Automated backup verification, periodic restore testing, geo-redundant backup storage, documented recovery runbooks, RTO/RPO monitoring',
    tef_low: 0.5, tef_ml: 1, tef_high: 3,
    vuln_low: 0.15, vuln_ml: 0.35, vuln_high: 0.60,
    primary_loss_low: 50000, primary_loss_ml: 300000, primary_loss_high: 1500000,
    secondary_event_prob: 0.10,
    secondary_loss_low: 0, secondary_loss_ml: 200000, secondary_loss_high: 1000000,
  },
  {
    id: 'tmpl-privilege-escalation',
    name: 'Privilege Escalation via Over-Provisioned Access',
    description: 'A user or attacker exploits overly broad access permissions to reach systems or data beyond their intended scope.',
    category: 'Identity & Access',
    scenario_family: 'Privileged access misuse',
    scenario_pattern: 'Over-provisioned access enables unauthorized actions',
    scenario_statement: 'User with over-provisioned access (or attacker who compromises such an account) leverages excessive permissions to access sensitive data or modify critical systems.',
    threat_community: 'Privileged administrator',
    threat_action: 'Access provisioning failure',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Operational backlog and productivity loss; Customer reimbursement / restitution',
    existing_controls_hint: 'Least-privilege access policies, quarterly access reviews, just-in-time access provisioning, role-based access control (RBAC), access certification campaigns',
    tef_low: 4, tef_ml: 12, tef_high: 30,
    vuln_low: 0.05, vuln_ml: 0.15, vuln_high: 0.30,
    primary_loss_low: 10000, primary_loss_ml: 75000, primary_loss_high: 350000,
    secondary_event_prob: 0.10,
    secondary_loss_low: 25000, secondary_loss_ml: 150000, secondary_loss_high: 1000000,
  },
  {
    id: 'tmpl-supply-chain-compromise',
    name: 'Software Supply Chain Compromise',
    description: 'A dependency, package, or vendor software update introduces malicious code into your environment.',
    category: 'Cyber Attack',
    scenario_family: 'Application security failure',
    scenario_pattern: 'Compromised software dependency introduces malicious code',
    scenario_statement: 'A trusted software dependency or vendor update is compromised, introducing malicious code that enables data access or system control.',
    threat_community: 'External attacker',
    threat_action: 'Insecure change / release',
    loss_event_type: 'Confidentiality loss',
    loss_forms: 'Incident response and investigation cost; Technology restoration / rebuild cost; Operational backlog and productivity loss; Reputation / brand harm',
    existing_controls_hint: 'Software composition analysis (SCA), dependency pinning, vendor security assessments, code signing verification, runtime application protection',
    tef_low: 1, tef_ml: 2, tef_high: 5,
    vuln_low: 0.05, vuln_ml: 0.15, vuln_high: 0.30,
    primary_loss_low: 50000, primary_loss_ml: 300000, primary_loss_high: 2000000,
    secondary_event_prob: 0.20,
    secondary_loss_low: 100000, secondary_loss_ml: 500000, secondary_loss_high: 5000000,
  },
  {
    id: 'tmpl-customer-ato',
    name: 'Customer Account Takeover',
    description: 'Attacker gains control of customer accounts using stolen credentials, enabling unauthorized transactions or data access.',
    category: 'Fraud',
    scenario_family: 'Identity compromise',
    scenario_pattern: 'Customer account takeover via credential compromise',
    scenario_statement: 'External attacker uses credential stuffing or phishing to take over customer accounts, enabling unauthorized transactions, data theft, or payment redirection.',
    threat_community: 'Account takeover',
    threat_action: 'Account takeover',
    loss_event_type: 'Fraud loss',
    loss_forms: 'Customer reimbursement / restitution; Fraud loss / unrecoverable funds; Incident response and investigation cost; Reputation / brand harm',
    existing_controls_hint: 'Customer MFA, device fingerprinting, login anomaly detection, credential breach monitoring, transaction velocity limits',
    tef_low: 10, tef_ml: 50, tef_high: 200,
    vuln_low: 0.01, vuln_ml: 0.03, vuln_high: 0.08,
    primary_loss_low: 5000, primary_loss_ml: 20000, primary_loss_high: 75000,
    secondary_event_prob: 0.05,
    secondary_loss_low: 25000, secondary_loss_ml: 100000, secondary_loss_high: 500000,
  },
  {
    id: 'tmpl-cloud-outage',
    name: 'Cloud Provider Regional Outage',
    description: 'Major cloud provider (AWS, Azure, GCP) experiences a regional outage affecting your infrastructure.',
    category: 'Resilience',
    scenario_family: 'Third-party dependency failure',
    scenario_pattern: 'Cloud provider regional outage disrupts services',
    scenario_statement: 'Cloud infrastructure provider experiences a regional outage, taking down production services that lack multi-region failover.',
    threat_community: 'Cloud platform dependency',
    threat_action: 'Dependency failure',
    loss_event_type: 'Availability loss',
    loss_forms: 'Operational backlog and productivity loss; Revenue loss from servicing disruption; Revenue loss from origination disruption; Contractual liability / partner indemnification',
    existing_controls_hint: 'Multi-region deployment, auto-failover configuration, degraded-mode procedures, cloud provider status monitoring, BCP testing',
    tef_low: 1, tef_ml: 3, tef_high: 6,
    vuln_low: 0.20, vuln_ml: 0.40, vuln_high: 0.70,
    primary_loss_low: 25000, primary_loss_ml: 150000, primary_loss_high: 750000,
    secondary_event_prob: 0.05,
    secondary_loss_low: 0, secondary_loss_ml: 100000, secondary_loss_high: 500000,
  },
  {
    id: 'tmpl-income-fraud',
    name: 'Income/Employment Misrepresentation',
    description: 'Applicant submits falsified income documents or employment verification to qualify for credit.',
    category: 'Fraud',
    scenario_family: 'Fraud / abuse',
    scenario_pattern: 'Applicant falsifies income to obtain credit',
    scenario_statement: 'First-party fraud applicant submits doctored pay stubs, bank statements, or employment letters to misrepresent financial position and obtain credit beyond their means.',
    threat_community: 'First-party fraud applicant',
    threat_action: 'Income / employment misrepresentation',
    loss_event_type: 'Fraud loss',
    loss_forms: 'Fraud loss / unrecoverable funds; Model remediation / re-underwriting cost; Operational backlog and productivity loss',
    existing_controls_hint: 'Automated income verification (VOI), employer verification services, bank statement analysis tools, document authenticity checks, fraud scoring',
    tef_low: 20, tef_ml: 60, tef_high: 150,
    vuln_low: 0.03, vuln_ml: 0.08, vuln_high: 0.15,
    primary_loss_low: 10000, primary_loss_ml: 35000, primary_loss_high: 80000,
    secondary_event_prob: 0.05,
    secondary_loss_low: 0, secondary_loss_ml: 100000, secondary_loss_high: 500000,
  },
];

export const TEMPLATE_CATEGORIES = [...new Set(SCENARIO_TEMPLATES.map((t) => t.category))];
